variables:
  IMAGE_NAME: "${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
  IMAGE_TAG: "${CI_PROJECT_NAME}.${CI_COMMIT_SHORT_SHA}"

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == "false"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - build
  - test
  - deploy

build static assets:
  stage: build
  image: node:16.20.2-bookworm
  artifacts:
    expire_in: "30 days"
    untracked: false
    access: all
    name: "static-build"
    when: on_success
    paths:
      - "dist"
  before_script:
    - npm install --global bun@1.1.7
    - bun --version
    - |-
      if [[ $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH ]]; then
        cp $ENV_FILE_PRODUCTION .env
      else
        cp $ENV_FILE .env
      fi
  script:
    - bun install --legacy-peer-deps
    - bun run build

run unit test:
  stage: test
  needs:
    - job: build static assets
      artifacts: true
  script:
    - |
      echo 'Unit test passed!'

run feature test:
  stage: test
  needs:
    - job: build static assets
      artifacts: true
  script:
    - |
      echo 'Feature test passed!'

run integration test:
  stage: test
  needs:
    - job: build static assets
      artifacts: true
  script:
    - |
      echo 'Integration test passed!'

.build_image:
  stage: deploy
  needs:
    - job: build static assets
      artifacts: true
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_JOB_TOKEN | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE --no-cache .
    - docker push $CI_REGISTRY_IMAGE --all-tags

build and push docker image:staging:
  extends: .build_image
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      variables:
        CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/master"

build and push docker image:production:
  extends: .build_image
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/production"

update deployments:
  tags:
    - proxmox-varnion
  stage: deploy
  image: ruby:3.1
  script:
    - |
      for f in $UPDATE_SERVER; do
        curl -sS "$f/v1/update" \
          -H "Authorization: Bearer $UPDATE_KEY"
      done

deploy to server:
  allow_failure: true
  tags:
    - proxmox-varnion
  when: manual
  stage: deploy
  needs: ["build and push docker image:production"]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE/production"
    COMMANDS:
      "echo $CI_JOB_TOKEN | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin &&
      docker ps -aqf name=$CI_PROJECT_NAME | xargs docker rm -f 2>/dev/null || true &&
      docker run --name $CI_PROJECT_NAME \
      --env APP_VERSION=$IMAGE_TAG \
      --publish $PUBLISH_PORT:80 \
      --restart unless-stopped \
      --pull=always \
      --detach \
      $CI_REGISTRY_IMAGE"
  before_script:
    - chmod 400 $SSH_PRIVATE_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY -p $SERVER_PORT $SERVER_USER@$SERVER_IP $COMMANDS
